server.port=8080

spring.application.name=api-gateway


spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0].name=JwtAuthFilter
spring.cloud.gateway.routes[0].filters[0].args.openPaths=POST:/api/auth/register,POST:/api/auth/login,POST:/api/auth/refresh,GET:/api/auth/search,GET:/api/auth/profile/**

spring.cloud.gateway.routes[1].id=post-service
spring.cloud.gateway.routes[1].uri=lb://post-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/posts/**
spring.cloud.gateway.routes[1].filters[0].name=JwtAuthFilter
spring.cloud.gateway.routes[1].filters[0].args.openPaths=GET:/api/posts/search,GET:/api/posts/{postId},GET:/api/posts/user/**,POST:/api/posts/*/likes/inc,POST:/api/posts/*/likes/dec,POST:/api/posts/*/comments/inc,POST:/api/posts/*/comments/dec

spring.cloud.gateway.routes[2].id=comment-service
spring.cloud.gateway.routes[2].uri=lb://comment-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/comments/**
spring.cloud.gateway.routes[2].filters[0].name=JwtAuthFilter
spring.cloud.gateway.routes[2].filters[0].args.openPaths=GET:/api/comments/post/**,GET:/api/comments/**,POST:/api/comments/*/like,POST:/api/comments/*/unlike

spring.cloud.gateway.routes[3].id=like-service
spring.cloud.gateway.routes[3].uri=lb://like-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/likes/**
spring.cloud.gateway.routes[3].filters[0].name=JwtAuthFilter
spring.cloud.gateway.routes[3].filters[0].args.openPaths=GET:/api/likes/target/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

jwt.secret=connectsphere-super-secret-key-replace-in-production-use-openssl-rand-hex-64

logging.level.com.connectsphere.gateway=DEBUG
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty.http.client=WARN