server.port=8082
spring.application.name=post-service

spring.datasource.url=jdbc:mysql://mysql-7981e4f-govindnacharya-2f14.h.aivencloud.com:3306/${AUTH_DB}?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.access-token-expiry-ms=900000

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true

logging.level.com.connectsphere=DEBUG
logging.level.org.springframework.security=INFO


spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${SPRING_RABBITMQ_VIRTUAL_HOST}

rabbitmq.exchange=${RABBITMQ_EXCHANGE}
rabbitmq.queue=${RABBITMQ_QUEUE}
rabbitmq.routing.key=${RABBITMQ_ROUTING_KEY}

spring.data.redis.url=${REDIS_URL}

app.feed.cache.ttl-seconds=300
app.feed.cache.post-ttl-seconds=1800
app.frontend-url=${FRONTEND_URL}
