server.port=8083
spring.application.name=comment-service

spring.datasource.url=jdbc:mysql://localhost:3306/connectsphere_auth?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

jwt.secret=connectsphere-super-secret-key-replace-in-production-use-openssl-rand-hex-64

services.post-service.base-url=http://localhost:8082
logging.level.com.connectsphere=DEBUG

rabbitmq.exchange=notification.exchange
rabbitmq.queue=notification.queue
rabbitmq.routing.key=notification.routing