server.port=8087
spring.application.name=media-service

spring.datasource.url=jdbc:mysql://mysql-7981e4f-govindnacharya-2f14.h.aivencloud.com:17307/${AUTH_DB}?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET}

spring.web.resources.static-locations=file:uploads/

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

cloudinary.folder.media=connectsphere/media
cloudinary.folder.stories=connectsphere/stories

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

logging.level.com.connectsphere=DEBUG

springdoc.api-docs.path=/v3/api-docs